#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import hashlib
import pickle
import sys
from functools import reduce
from typing import TypeVar, List, Tuple, Dict, Any
from uuid import uuid4

T = TypeVar('T')


def unzip(xs: List[Tuple[List[T], List[T]]]) -> Tuple[List[List[T]], List[List[T]]]:
    return list(zip(*xs))


def log(msg: str) -> None:
    print(msg, file=sys.stderr)


def merge_dicts(*args: Dict) -> Dict[Any, Any]:
    return reduce(lambda x, y: {**x, **y}, args)


def uuid_to_str(uuid: uuid4) -> str:
    return str(uuid).replace('-', '')


def hash_dict(d: Dict) -> str:
    dict_str_rep = '_'.join([f'{key}_{d[key]}' for key in sorted(d.keys())])
    return hashlib.sha224(bytearray(dict_str_rep, 'utf8')).hexdigest()


def pickle_object(obj: object, path: str) -> None:
    pickle.dump(obj, open(path, 'wb'))


def unpickle(path: str) -> Any:
    return pickle.load(open(path, 'rb'))


stopwords = {'a',
             'about',
             'above',
             'after',
             'again',
             'against',
             'ain',
             'all',
             'am',
             'an',
             'and',
             'any',
             'are',
             'aren',
             "aren't",
             'as',
             'at',
             'be',
             'because',
             'been',
             'before',
             'being',
             'below',
             'between',
             'both',
             'but',
             'by',
             'can',
             'couldn',
             "couldn't",
             'd',
             'did',
             'didn',
             "didn't",
             'do',
             'does',
             'doesn',
             "doesn't",
             'doing',
             'don',
             "don't",
             'down',
             'during',
             'each',
             'few',
             'for',
             'from',
             'further',
             'had',
             'hadn',
             "hadn't",
             'has',
             'hasn',
             "hasn't",
             'have',
             'haven',
             "haven't",
             'having',
             'he',
             'her',
             'here',
             'hers',
             'herself',
             'him',
             'himself',
             'his',
             'how',
             'i',
             'if',
             'in',
             'into',
             'is',
             'isn',
             "isn't",
             'it',
             "it's",
             'its',
             'itself',
             'just',
             'll',
             'm',
             'ma',
             'me',
             'mightn',
             "mightn't",
             'more',
             'most',
             'mustn',
             "mustn't",
             'my',
             'myself',
             'needn',
             "needn't",
             'no',
             'nor',
             'not',
             'now',
             'o',
             'of',
             'off',
             'on',
             'once',
             'only',
             'or',
             'other',
             'our',
             'ours',
             'ourselves',
             'out',
             'over',
             'own',
             're',
             's',
             'same',
             'shan',
             "shan't",
             'she',
             "she's",
             'should',
             "should've",
             'shouldn',
             "shouldn't",
             'so',
             'some',
             'such',
             't',
             'than',
             'that',
             "that'll",
             'the',
             'their',
             'theirs',
             'them',
             'themselves',
             'then',
             'there',
             'these',
             'they',
             'this',
             'those',
             'through',
             'to',
             'too',
             'under',
             'until',
             'up',
             've',
             'very',
             'was',
             'wasn',
             "wasn't",
             'we',
             'were',
             'weren',
             "weren't",
             'what',
             'when',
             'where',
             'which',
             'while',
             'who',
             'whom',
             'why',
             'will',
             'with',
             'won',
             "won't",
             'wouldn',
             "wouldn't",
             'y',
             'you',
             "you'd",
             "you'll",
             "you're",
             "you've",
             'your',
             'yours',
             'yourself',
             'yourselves'}
